import Head from "next/head";
import Image from "next/image";
import { Poppins } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import Link from "next/link";
import { ParsedUrlQuery } from "querystring";

export type TeamsType = {
  _id: string;
  name: string;
  image: string;
};

interface ITeamsProps {
  teams: TeamsType[];

}

export default function Home({ teams }: ITeamsProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {teams.map((team) => (
          <>
            <Link href={`/teams/${team._id}`}>
              info
            </Link>
            <Link href={`/team/${team._id}`}>
              <img
                src={team.image}
                alt={team.name}
                width={150}
                height={150}
              />
              <h2>{team.name}</h2>
            </Link>
          </>
        ))}
      </main>
    </>
  );
}


type Params = {
  id: string;
} & ParsedUrlQuery;

export const getStaticProps: GetStaticProps = async (context) => {
  const response = await fetch("https://api-products-dh-next.vercel.app/teams");
  const teams = await response.json();

  // console.log(teams);
 
  return {
    props: { teams},
  };
};
