import Head from "next/head";
import { TasksType } from "@/utils/types";
import Link from "next/link";

type PropsType = {
  tasks: TasksType[];
};

export default function Home(props: PropsType) {
  const { tasks } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen grid content-center justify-center  bg-zinc-900">
        <div className="w-[375px] md:w-[500px] min-h-[500px] bg-blue-900 rounded">

            <h1 className="text-2xl py-4 px-4">Minhas tarefas</h1>
            <button className="ml-2 border bg-blue-400 py-2 px-2 rounded-sm">
              <Link href="/tasks/create">Adicionar tarefa</Link>
            </button>

          <div className="py-6 px-2 grid gap-2">
            {tasks.map((task) => (
              <div
                key={task._id}
                className="border border-blue-400 bg-blue-300 py-2"
              >
                <Link href={`/tasks/${task._id}`}>
                  <h2 className="px-2">
                    {task.item} -{" "}
                    {task.completed ? "finalizado" : "não finalizado"}
                  </h2>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch(process.env.API_URL as string);
  const tasks = await response.json();
  console.log(tasks);

  return {
    props: {
      tasks,
    },
  };
};
