import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage } from "next"
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })


interface Characters{
  results:Character[]
}

interface Character {
  id: number,
  name: string,
}

interface Props {
  characters: Characters
}


 const Home:NextPage<Props> = ({characters}) => {
  return (
    <>
      <Head>
        <title>Character</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Characters</h1>
        <ul>
          {characters?.results.length 
            ? characters?.results.map((character)=> (
              <Link href={`/character/${character.id}`} key={character.id}
              >
                <li>
                  <p>{character.name}</p>
                </li>
              </Link>
              ))
            : null
          }
        </ul>
      </main>
    </>
  )
}


export const getStaticProps = async()=>{
  const res = await fetch("https://rickandmortyapi.com/api/character/")
  const data = await res.json()

  return{ props:{characters: data }}
}



export default Home