import Head from "next/head";
import { FormEventHandler } from "react";
import styles from "../styles/Home.module.css";

type TaskType = {
  _id: number;
  title: string;
  description: string;
};

type Props = {
  tasks: TaskType[];
};

const handleSubmit:FormEventHandler<HTMLFormElement> = async (event) => {
  event.preventDefault();

}

export default function Home({ tasks }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <form className={styles.form} onSubmit={handleSubmit}>
            <h2>Criar tarefa</h2>
            <label htmlFor="name">Título</label>
            <input type="text" name="name" id="name" />
            <label htmlFor="description">Descrição</label>
            <input type="text" name="description" id="description" />
            <button>Salvar</button>
          </form>
        </div>
        
        <div>
          <ul>
            {tasks.map((task) => (
              <>
                <li key={task._id}>{task.title}</li>
                <p>{task.description}</p>
              </>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3000/api/tasks");
  const tasks = await response.json();

  return { props: { tasks } };
}

//Ns9BCNOavo5phtge admin


